name: getxfire
description: A Flutter Package that implemented firebase services with getx package.
version: 0.3.3
homepage: https://github.com/faisalramdan17/getxfire/wiki
repository: https://github.com/faisalramdan17/getxfire

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_storage: ^10.2.5
  firebase_dynamic_links: ^4.0.4
  firebase_analytics: ^9.0.5
  # firebase_messaging: ^11.2.5 # Coming Soon

  # SignIn Packages  
  google_sign_in: ^5.2.1
  # flutter_facebook_auth: ^3.4.0 # Coming Soon
  # sign_in_with_apple: ^3.0.0 # Coming Soon

  # Utillities Packages
  intl: ^0.17.0
  get: ^4.6.1
  get_storage: ^2.0.3
  image_picker: ^0.8.4+4
  image_cropper: ^1.4.1
  flutter_web_browser: ^0.16.0

  # UI Packages
  lottie: ^1.2.1
  font_awesome_flutter: ^9.2.0
  flutter_animated_dialog: ^2.0.1
  flutter_spinkit: ^5.1.0
  
  # flutter_image_compress: ^1.0.0
  # permission_handler: ^8.0.0+2
  # path: ^1.8.0
  # path_provider: ^2.0.2
  # dio: ^4.0.0
  # location: ^4.1.1
  # geoflutterfire: ^3.0.0-nullsafety.4
  # rxdart: ^0.27.0 # Needs to be updated when geoflutterfire changes.
  # crypto: ^3.0.1 # md5 on chat, facebook  login
  # algolia: ^1.0.1
  # merge_map: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
 - /admin-vuejs/config.ts
 - /example/android/app/google-services.json
 - /example/ios/Runner/GoogleService-Info.plist
 - /example/web/index.html

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: id.codingyourlife.getxfire
        pluginClass: GetxfirePlugin
      ios:
        pluginClass: GetxfirePlugin
      macos:
        pluginClass: GetxfirePlugin
      web:
        pluginClass: GetxfireWeb
        fileName: getxfire_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  assets:
   - assets/lottie/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
